/* eslint-disable */
export const publicKey = `-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC36xxkZcmppT5zVERIp4nCg89i/F2/gOiWOeARHHUOrMc5euB+cOfsjUDCWHQg4vteeASHua5Yx89vTm7mN52MYKLaqZYBBsyPjVpmGmhlel3XHGXHIzJ3ZmQwwKMh6vguWHvUFPU8/IiRFyKSaPmPp1CnsdXs6SKBWoiCLSiXiQIDAQAB
-----END PUBLIC KEY-----
`;
// export const publicKey = `-----BEGIN PUBLIC KEY-----
// MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCU56IKlA822Stn8HKDHRSYPS2y5IjkQh+JlauQDnnv/aREIO42waSyf/awYa0+5fFYww7dpUxWxqVx0XL64+UKs6LPLCkj2cZFrYNWorPdDJ5Gj9JHJkwp95eGULgc49JLWYMQb+zRe54nxbFukhYFHjPvgB1+AUu4uojkzcagDQIDAQAB
// -----END PUBLIC KEY-----
// `;
// export const publicKey = `-----BEGIN PUBLIC KEY-----
// WjmCloiJ3jqs5WTMIwmzJKaLo73X9UVvhPbrjv+SmVp1R0UpKqC2eRewyC7xMoxu5fk96FiWq9hFQ6po3uVoN+jaEG5YMYxC7NDWYyUrhyuMiuVEsd9YEeGXL5WL01TfGQxq0KsypnqzYSAwNK63a+tkD2iZQNp+P3Sa3yUq1d8=
// -----END PUBLIC KEY-----`
