export enum CacheKeys {
  selfModuleTabKey = 'selfTabKey',
  quoteTab = 'quoteTab',
  settingTab = 'setting_tab',
  personalCenterTab = 'personal_center_tab',
  language = 'language',
  fontSize = 'APP.font',
  upDownColor = 'QUOTATION.upDownColor',
  priceTwinkle = 'QUOTATION.priceTwinkle',
  autoLogin = 'AUTO_LOGIN.autoLogin',
  timeout = 'AUTO_LOGIN.timeout',
  optionalPush = 'MESSAGE_NOTIFY.optionalPush',
  token = 'token',
  userInfo = 'user_info',
  globalModal = 'global_modal',
  historyLoginRecord = 'history_login_record',
  stockGlobalSearchHistory = 'quote_stock_global_search_history',
  stockTurnerList = 'quote_stock_turner_list',
  quoteGatewayWSAddress = 'quote_gateway_WSAddress',
  quoteChartIndicatorsParamsList = 'quote_chartIndicators_params_list', // 指标设置
  deviceNo = 'device_no',
  handicapShowMore = 'handicap_show_more',
  quoteChartPeriod = 'quote_chart_period',
  quoteChartPeriodType = 'quote_chart_period_type',
}
