export default [
  { letter: 'L', nameTw: '老虎證券', name: '老虎证券', ccass: 'B02142' },
  { letter: 'F', nameTw: '富途證券', name: '富途证券', ccass: 'B01955' },
  { letter: 'H', nameTw: '海通國際證券', name: '海通国际证券 ', ccass: 'B01143' },
  { letter: 'Y', nameTw: '盈透證券', name: '盈透证券', ccass: 'B01590' },
  { letter: 'Y', nameTw: '耀才證券', name: '耀才证券', ccass: 'B01668' },
  { letter: 'Z', nameTw: '中信建投(國際)證券', name: '中信建投(国际)证券', ccass: 'B01962' },
  { letter: 'Z', nameTw: '招商證券（香港）', name: '招商证券（香港）', ccass: 'B01148' },
  { letter: 'G', nameTw: '國信證券（香港）', name: '国信证券（香港）', ccass: 'B01890' },
  { letter: 'A', nameTw: '艾德證券期貨', name: '艾德证券期货', ccass: 'B02047' },
  { letter: 'S', nameTw: '時富證券', name: '时富证券', ccass: 'B01119' },
  { letter: 'N', nameTw: '南華證券', name: '南华证券', ccass: 'B01289' },
  { letter: 'J', nameTw: '金利豐證券', name: '金利丰证券', ccass: 'B01438' },
  { letter: 'Y', nameTw: '永豐證券', name: '永丰证券', ccass: 'B01351' },
  { letter: 'Z', nameTw: '尊嘉證券', name: '尊嘉证券', ccass: 'B02102' },
  { letter: 'Z', nameTw: '中銀國際證券', name: '中银国际证券', ccass: 'B01130' },
  { letter: 'S', nameTw: '勝利證券', name: '胜利证券', ccass: 'B01445' },
  { letter: 'G', nameTw: '廣發行證券', name: '广发行证券', ccass: 'B01543' },
  { letter: 'Z', nameTw: '中金三甲證券', name: '中金三甲证券', ccass: 'B01821' },
  { letter: 'Y', nameTw: '銀河—聯昌證券(香港)', name: '银河—联昌证券(香港)', ccass: 'B01347' },
  { letter: 'Y', nameTw: '盈立證券', name: '盈立证券', ccass: 'B02159' },
  { letter: 'G', nameTw: '國泰君安證券(香港)', name: '国泰君安证券(香港)', ccass: 'B01565' },
  { letter: 'D', nameTw: '東方證券(香港)', name: '东方证券(香港)', ccass: 'B01900' },
  { letter: 'G', nameTw: '光大證券(香港)', name: '光大证券(香港)', ccass: 'B01086' },
  { letter: 'Z', nameTw: '中泰國際證券', name: '中泰国际证券', ccass: 'B01959' },
  { letter: 'H', nameTw: '華盛資本證券', name: '华盛资本证券', ccass: 'B01904' },
  { letter: 'C', nameTw: '創興證券', name: '创兴证券', ccass: 'B01183' },
  { letter: 'D', nameTw: '東亞證券', name: '东亚证券', ccass: 'B01118' },
  { letter: 'Z', nameTw: '渣打證券(香港)', name: '渣打证券(香港)', ccass: 'B01078' },
  { letter: 'H', nameTw: '輝立證券(香港)', name: '辉立证券(香港)', ccass: 'B01345' },
  { letter: 'N', nameTw: '農銀國際證券', name: '农银国际证券', ccass: 'B01564' },
  { letter: 'Z', nameTw: '致富證券', name: '致富证券', ccass: 'B01584' },
];
